"""Offline fine-tuning for the synthetic RU/KZ ticket classifier.

The scenario-disjoint splits are generated by scripts/generate_synthetic_classifier.py.
This script does not promote a model or use operator feedback.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import torch
from torch.utils.data import DataLoader, TensorDataset
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from app.constants import TOPICS

LABELS = tuple(topic.topic_id for topic in TOPICS if topic.topic_id != "other")


def read_split(path: Path, split: str) -> list[dict[str, str]]:
    rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if not rows:
        raise ValueError(f"empty split: {path}")
    for row in rows:
        if row.get("split") != split or row.get("topic_id") not in LABELS:
            raise ValueError(f"invalid split or label in {path}")
        if row.get("language") not in {"RU", "KZ"} or row.get("synthetic") is not True:
            raise ValueError(f"expected synthetic RU/KZ rows in {path}")
        if not row.get("text") or not row.get("scenario_id"):
            raise ValueError(f"missing text or scenario_id in {path}")
    return rows


def validate_splits(splits: dict[str, list[dict[str, str]]]) -> None:
    seen_scenarios: set[str] = set()
    seen_texts: set[str] = set()
    for name, rows in splits.items():
        scenarios = {row["scenario_id"] for row in rows}
        texts = {" ".join(row["text"].casefold().split()) for row in rows}
        if seen_scenarios & scenarios or seen_texts & texts:
            raise ValueError(f"scenario or text leakage into {name}")
        if {row["topic_id"] for row in rows} != set(LABELS):
            raise ValueError(f"missing class in {name}")
        if {row["language"] for row in rows} != {"RU", "KZ"}:
            raise ValueError(f"missing language in {name}")
        seen_scenarios.update(scenarios)
        seen_texts.update(texts)


def make_loader(rows: list[dict[str, str]], tokenizer, batch_size: int, max_length: int, shuffle: bool) -> DataLoader:
    encoded = tokenizer(
        [row["text"] for row in rows],
        padding="max_length",
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )
    labels = torch.tensor([LABELS.index(row["topic_id"]) for row in rows], dtype=torch.long)
    dataset = TensorDataset(encoded["input_ids"], encoded["attention_mask"], labels)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, pin_memory=torch.cuda.is_available())


def score(actual: list[str], predicted: list[str]) -> dict:
    per_class = {}
    for label in LABELS:
        tp = sum(a == label and p == label for a, p in zip(actual, predicted))
        fp = sum(a != label and p == label for a, p in zip(actual, predicted))
        fn = sum(a == label and p != label for a, p in zip(actual, predicted))
        denominator = 2 * tp + fp + fn
        per_class[label] = round(2 * tp / denominator, 6) if denominator else 0.0
    return {
        "accuracy": round(sum(a == p for a, p in zip(actual, predicted)) / len(actual), 6),
        "macro_f1": round(sum(per_class.values()) / len(per_class), 6),
        "per_class_f1": per_class,
    }


@torch.inference_mode()
def evaluate(model, loader: DataLoader, rows: list[dict[str, str]], device: torch.device) -> dict:
    model.eval()
    predicted: list[str] = []
    for input_ids, attention_mask, _ in loader:
        logits = model(input_ids=input_ids.to(device), attention_mask=attention_mask.to(device)).logits
        predicted.extend(LABELS[index] for index in logits.argmax(dim=-1).tolist())
    actual = [row["topic_id"] for row in rows]
    metrics = score(actual, predicted)
    metrics["by_language"] = {
        language: score(
            [a for a, row in zip(actual, rows) if row["language"] == language],
            [p for p, row in zip(predicted, rows) if row["language"] == language],
        )
        for language in ("RU", "KZ")
    }
    metrics["sample_count"] = len(rows)
    metrics["scenario_count"] = len({row["scenario_id"] for row in rows})
    return metrics


@torch.inference_mode()
def collect_logits(model, loader: DataLoader, device: torch.device) -> tuple[torch.Tensor, torch.Tensor]:
    model.eval()
    logits = []
    labels = []
    for input_ids, attention_mask, batch_labels in loader:
        logits.append(model(input_ids=input_ids.to(device), attention_mask=attention_mask.to(device)).logits.float())
        labels.append(batch_labels.to(device))
    return torch.cat(logits), torch.cat(labels)


def fit_temperature(logits: torch.Tensor, labels: torch.Tensor) -> float:
    """Minimize validation NLL without using the held-out test split."""
    best_temperature = 1.0
    best_loss = float("inf")
    for index in range(10, 201):
        temperature = index / 10
        loss = torch.nn.functional.cross_entropy(logits / temperature, labels).item()
        if loss < best_loss:
            best_loss = loss
            best_temperature = temperature
    return best_temperature


def calibration_metrics(logits: torch.Tensor, labels: torch.Tensor, temperature: float) -> dict:
    probabilities = torch.softmax(logits / temperature, dim=-1)
    return {
        "nll": round(torch.nn.functional.cross_entropy(logits / temperature, labels).item(), 6),
        "mean_confidence": round(probabilities.max(dim=-1).values.mean().item(), 6),
        "accuracy": round((probabilities.argmax(dim=-1) == labels).float().mean().item(), 6),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path("data/sdg/generated/classifier_v1"))
    parser.add_argument("--output-dir", type=Path, default=Path("ml-service/artifacts/classifier-synthetic-v1"))
    parser.add_argument("--base-model", default="FacebookAI/xlm-roberta-base")
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--max-length", type=int, default=96)
    parser.add_argument("--learning-rate", type=float, default=2e-5)
    args = parser.parse_args()
    if args.epochs < 1 or args.batch_size < 1 or args.max_length < 16:
        parser.error("epochs and batch-size must be positive; max-length must be at least 16")

    random.seed(109)
    torch.manual_seed(109)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(109)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(json.dumps({"stage": "start", "device": str(device), "base_model": args.base_model}), flush=True)

    splits = {name: read_split(args.data_dir / f"{name}.jsonl", name) for name in ("train", "validation", "test")}
    validate_splits(splits)
    dataset_hash = hashlib.sha256()
    for name in splits:
        dataset_hash.update((args.data_dir / f"{name}.jsonl").read_bytes())
    tokenizer = AutoTokenizer.from_pretrained(args.base_model)
    model = AutoModelForSequenceClassification.from_pretrained(
        args.base_model,
        num_labels=len(LABELS),
        id2label={index: label for index, label in enumerate(LABELS)},
        label2id={label: index for index, label in enumerate(LABELS)},
    ).to(device)
    train_loader = make_loader(splits["train"], tokenizer, args.batch_size, args.max_length, True)
    validation_loader = make_loader(splits["validation"], tokenizer, args.batch_size * 2, args.max_length, False)
    test_loader = make_loader(splits["test"], tokenizer, args.batch_size * 2, args.max_length, False)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate)
    use_amp = device.type == "cuda"
    scaler = torch.amp.GradScaler("cuda", enabled=use_amp)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    best_f1 = -1.0
    best_validation: dict = {}
    for epoch in range(args.epochs):
        model.train()
        losses = []
        for step, (input_ids, attention_mask, labels) in enumerate(train_loader, 1):
            optimizer.zero_grad(set_to_none=True)
            with torch.autocast(device_type=device.type, dtype=torch.float16, enabled=use_amp):
                loss = model(
                    input_ids=input_ids.to(device),
                    attention_mask=attention_mask.to(device),
                    labels=labels.to(device),
                ).loss
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            losses.append(loss.item())
            if step % 250 == 0:
                print(json.dumps({"stage": "train", "epoch": epoch + 1, "step": step, "steps": len(train_loader), "loss": round(sum(losses[-250:]) / min(len(losses), 250), 4)}), flush=True)
        validation = evaluate(model, validation_loader, splits["validation"], device)
        print(json.dumps({"stage": "validation", "epoch": epoch + 1, "macro_f1": validation["macro_f1"], "accuracy": validation["accuracy"]}), flush=True)
        if validation["macro_f1"] > best_f1:
            best_f1 = validation["macro_f1"]
            best_validation = validation
            model.save_pretrained(args.output_dir, safe_serialization=True)
            tokenizer.save_pretrained(args.output_dir)

    model = AutoModelForSequenceClassification.from_pretrained(args.output_dir).to(device)
    validation_logits, validation_labels = collect_logits(model, validation_loader, device)
    temperature = fit_temperature(validation_logits, validation_labels)
    best_validation["calibration"] = calibration_metrics(validation_logits, validation_labels, temperature)
    test = evaluate(model, test_loader, splits["test"], device)
    test_logits, test_labels = collect_logits(model, test_loader, device)
    test["calibration"] = calibration_metrics(test_logits, test_labels, temperature)
    model_file = args.output_dir / "model.safetensors"
    with model_file.open("rb") as stream:
        checksum = hashlib.file_digest(stream, "sha256").hexdigest()
    version = f"classifier-xlm-r-synthetic-v1-{checksum[:12]}-t{round(temperature * 10):03d}"
    metadata = {
        "model_version": version,
        "model_family": "xlm-roberta-sequence-classification",
        "base_model": args.base_model,
        "dataset_version": f"classifier-synthetic-v1-sha256:{dataset_hash.hexdigest()[:12]}",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "metrics": {"status": "synthetic_holdout_only", "validation": best_validation, "test": test},
        "languages": ["RU", "KZ"],
        "labels": list(LABELS),
        "training_config": {
            "epochs": args.epochs,
            "batch_size": args.batch_size,
            "max_length": args.max_length,
            "learning_rate": args.learning_rate,
            "temperature": temperature,
            "seed": 109,
            "train_samples": len(splits["train"]),
            "train_scenarios": len({row["scenario_id"] for row in splits["train"]}),
            "class_counts": dict(Counter(row["topic_id"] for row in splits["train"])),
            "online_retraining": False,
        },
        "artifact_checksum": f"sha256:{checksum}",
    }
    (args.output_dir / "manifest.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"stage": "complete", "model_version": version, "validation_macro_f1": best_f1, "test_macro_f1": test["macro_f1"], "test_accuracy": test["accuracy"]}), flush=True)


if __name__ == "__main__":
    main()
